version: '3.8'

services:
  car-dealership:
    image: car-dealership:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: car-dealership-app
